export const countryCodes = [
  { code: '+93', country: 'Afghanistan', countryar: 'أفغانستان', flag: '🇦🇫' },
  { code: '+355', country: 'Albania', countryar: 'ألبانيا', flag: '🇦🇱' },
  { code: '+213', country: 'Algeria', countryar: 'الجزائر', flag: '🇩🇿' },
  { code: '+1-684', country: 'American Samoa', countryar: 'ساموا الأمريكية', flag: '🇦🇸' },
  { code: '+376', country: 'Andorra', countryar: 'أندورا', flag: '🇦🇩' },
  { code: '+244', country: 'Angola', countryar: 'أنغولا', flag: '🇦🇴' },
  { code: '+1-264', country: 'Anguilla', countryar: 'أنغيلا', flag: '🇦🇮' },
  { code: '+672', country: 'Antarctica', countryar: 'القارة القطبية الجنوبية', flag: '🇦🇶' },
  { code: '+1-268', country: 'Antigua and Barbuda', countryar: 'أنتيغوا وبربودا', flag: '🇦🇬' },
  { code: '+54', country: 'Argentina', countryar: 'الأرجنتين', flag: '🇦🇷' },
  { code: '+374', country: 'Armenia', countryar: 'أرمينيا', flag: '🇦🇲' },
  { code: '+297', country: 'Aruba', countryar: 'أروبا', flag: '🇦🇼' },
  { code: '+61', country: 'Australia', countryar: 'أستراليا', flag: '🇦🇺' },
  { code: '+43', country: 'Austria', countryar: 'النمسا', flag: '🇦🇹' },
  { code: '+994', country: 'Azerbaijan', countryar: 'أذربيجان', flag: '🇦🇿' },
  { code: '+1-242', country: 'Bahamas', countryar: 'الباهاما', flag: '🇧🇸' },
  { code: '+973', country: 'Bahrain', countryar: 'البحرين', flag: '🇧🇭' },
  { code: '+880', country: 'Bangladesh', countryar: 'بنغلاديش', flag: '🇧🇩' },
  { code: '+1-246', country: 'Barbados', countryar: 'بربادوس', flag: '🇧🇧' },
  { code: '+375', country: 'Belarus', countryar: 'بيلاروسيا', flag: '🇧🇾' },
  { code: '+32', country: 'Belgium', countryar: 'بلجيكا', flag: '🇧🇪' },
  { code: '+501', country: 'Belize', countryar: 'بليز', flag: '🇧🇿' },
  { code: '+229', country: 'Benin', countryar: 'بنين', flag: '🇧🇯' },
  { code: '+1-441', country: 'Bermuda', countryar: 'برمودا', flag: '🇧🇲' },
  { code: '+975', country: 'Bhutan', countryar: 'بوتان', flag: '🇧🇹' },
  { code: '+591', country: 'Bolivia', countryar: 'بوليفيا', flag: '🇧🇴' },
  { code: '+387', country: 'Bosnia and Herzegovina', countryar: 'البوسنة والهرسك', flag: '🇧🇦' },
  { code: '+267', country: 'Botswana', countryar: 'بوتسوانا', flag: '🇧🇼' },
  { code: '+55', country: 'Brazil', countryar: 'البرازيل', flag: '🇧🇷' },
  { code: '+246', country: 'British Indian Ocean Territory', countryar: 'إقليم المحيط الهندي البريطاني', flag: '🇮🇴' },
  { code: '+1-284', country: 'British Virgin Islands', countryar: 'جزر فيرجن البريطانية', flag: '🇻🇬' },
  { code: '+673', country: 'Brunei', countryar: 'بروناي', flag: '🇧🇳' },
  { code: '+359', country: 'Bulgaria', countryar: 'بلغاريا', flag: '🇧🇬' },
  { code: '+226', country: 'Burkina Faso', countryar: 'بوركينا فاسو', flag: '🇧🇫' },
  { code: '+257', country: 'Burundi', countryar: 'بوروندي', flag: '🇧🇮' },
  { code: '+855', country: 'Cambodia', countryar: 'كمبوديا', flag: '🇰🇭' },
  { code: '+237', country: 'Cameroon', countryar: 'الكاميرون', flag: '🇨🇲' },
  { code: '+1', country: 'Canada', countryar: 'كندا', flag: '🇨🇦' },
  { code: '+238', country: 'Cape Verde', countryar: 'الرأس الأخضر', flag: '🇨🇻' },
  { code: '+1-345', country: 'Cayman Islands', countryar: 'جزر كايمان', flag: '🇰🇾' },
  { code: '+236', country: 'Central African Republic', countryar: 'جمهورية أفريقيا الوسطى', flag: '🇨🇫' },
  { code: '+235', country: 'Chad', countryar: 'تشاد', flag: '🇹🇩' },
  { code: '+56', country: 'Chile', countryar: 'تشيلي', flag: '🇨🇱' },
  { code: '+86', country: 'China', countryar: 'الصين', flag: '🇨🇳' },
  { code: '+61', country: 'Christmas Island', countryar: 'جزيرة كريسماس', flag: '🇨🇽' },
  { code: '+61', country: 'Cocos Islands', countryar: 'جزر كوكوس', flag: '🇨🇨' },
  { code: '+57', country: 'Colombia', countryar: 'كولومبيا', flag: '🇨🇴' },
  { code: '+269', country: 'Comoros', countryar: 'جزر القمر', flag: '🇰🇲' },
  { code: '+682', country: 'Cook Islands', countryar: 'جزر كوك', flag: '🇨🇰' },
  { code: '+506', country: 'Costa Rica', countryar: 'كوستاريكا', flag: '🇨🇷' },
  { code: '+385', country: 'Croatia', countryar: 'كرواتيا', flag: '🇭🇷' },
  { code: '+53', country: 'Cuba', countryar: 'كوبا', flag: '🇨🇺' },
  { code: '+599', country: 'Curaçao', countryar: 'كوراساو', flag: '🇨🇼' },
  { code: '+357', country: 'Cyprus', countryar: 'قبرص', flag: '🇨🇾' },
  { code: '+420', country: 'Czech Republic', countryar: 'التشيك', flag: '🇨🇿' },
  { code: '+243', country: 'Democratic Republic of the Congo', countryar: 'جمهورية الكونغو الديمقراطية', flag: '🇨🇩' },
  { code: '+45', country: 'Denmark', countryar: 'الدنمارك', flag: '🇩🇰' },
  { code: '+253', country: 'Djibouti', countryar: 'جيبوتي', flag: '🇩🇯' },
  { code: '+1-767', country: 'Dominica', countryar: 'دومينيكا', flag: '🇩🇲' },
  { code: '+1-809', country: 'Dominican Republic', countryar: 'جمهورية الدومينيكان', flag: '🇩🇴' },
  { code: '+670', country: 'East Timor', countryar: 'تيمور الشرقية', flag: '🇹🇱' },
  { code: '+593', country: 'Ecuador', countryar: 'الإكوادور', flag: '🇪🇨' },
  { code: '+20', country: 'Egypt', countryar: 'مصر', flag: '🇪🇬' },
  { code: '+503', country: 'El Salvador', countryar: 'السلفادور', flag: '🇸🇻' },
  { code: '+240', country: 'Equatorial Guinea', countryar: 'غينيا الاستوائية', flag: '🇬🇶' },
  { code: '+291', country: 'Eritrea', countryar: 'إريتريا', flag: '🇪🇷' },
  { code: '+372', country: 'Estonia', countryar: 'إستونيا', flag: '🇪🇪' },
  { code: '+251', country: 'Ethiopia', countryar: 'إثيوبيا', flag: '🇪🇹' },
  { code: '+500', country: 'Falkland Islands', countryar: 'جزر فوكلاند', flag: '🇫🇰' },
  { code: '+298', country: 'Faroe Islands', countryar: 'جزر فارو', flag: '🇫🇴' },
  { code: '+679', country: 'Fiji', countryar: 'فيجي', flag: '🇫🇯' },
  { code: '+358', country: 'Finland', countryar: 'فنلندا', flag: '🇫🇮' },
  { code: '+33', country: 'France', countryar: 'فرنسا', flag: '🇫🇷' },
  { code: '+594', country: 'French Guiana', countryar: 'غويانا الفرنسية', flag: '🇬🇫' },
  { code: '+689', country: 'French Polynesia', countryar: 'بولينيزيا الفرنسية', flag: '🇵🇫' },
  { code: '+241', country: 'Gabon', countryar: 'الغابون', flag: '🇬🇦' },
  { code: '+220', country: 'Gambia', countryar: 'غامبيا', flag: '🇬🇲' },
  { code: '+995', country: 'Georgia', countryar: 'جورجيا', flag: '🇬🇪' },
  { code: '+49', country: 'Germany', countryar: 'ألمانيا', flag: '🇩🇪' },
  { code: '+233', country: 'Ghana', countryar: 'غانا', flag: '🇬🇭' },
  { code: '+350', country: 'Gibraltar', countryar: 'جبل طارق', flag: '🇬🇮' },
  { code: '+30', country: 'Greece', countryar: 'اليونان', flag: '🇬🇷' },
  { code: '+299', country: 'Greenland', countryar: 'جرينلاند', flag: '🇬🇱' },
  { code: '+1-473', country: 'Grenada', countryar: 'غرينادا', flag: '🇬🇩' },
  { code: '+590', country: 'Guadeloupe', countryar: 'جوادلوب', flag: '🇬🇵' },
  { code: '+1-671', country: 'Guam', countryar: 'غوام', flag: '🇬🇺' },
  { code: '+502', country: 'Guatemala', countryar: 'غواتيمالا', flag: '🇬🇹' },
  { code: '+44-1481', country: 'Guernsey', countryar: 'جيرزي', flag: '🇬🇬' },
  { code: '+224', country: 'Guinea', countryar: 'غينيا', flag: '🇬🇳' },
  { code: '+245', country: 'Guinea-Bissau', countryar: 'غينيا بيساو', flag: '🇬🇼' },
  { code: '+592', country: 'Guyana', countryar: 'غيانا', flag: '🇬🇾' },
  { code: '+509', country: 'Haiti', countryar: 'هايتي', flag: '🇭🇹' },
  { code: '+504', country: 'Honduras', countryar: 'هندوراس', flag: '🇭🇳' },
  { code: '+852', country: 'Hong Kong', countryar: 'هونغ كونغ', flag: '🇭🇰' },
  { code: '+36', country: 'Hungary', countryar: 'المجر', flag: '🇭🇺' },
  { code: '+354', country: 'Iceland', countryar: 'آيسلندا', flag: '🇮🇸' },
  { code: '+91', country: 'India', countryar: 'الهند', flag: '🇮🇳' },
  { code: '+62', country: 'Indonesia', countryar: 'إندونيسيا', flag: '🇮🇩' },
  { code: '+98', country: 'Iran', countryar: 'إيران', flag: '🇮🇷' },
  { code: '+964', country: 'Iraq', countryar: 'العراق', flag: '🇮🇶' },
  { code: '+353', country: 'Ireland', countryar: 'أيرلندا', flag: '🇮🇪' },
  { code: '+44-1624', country: 'Isle of Man', countryar: 'جزيرة مان', flag: '🇮🇲' },
  { code: '+972', country: 'Israel', countryar: 'إسرائيل', flag: '🇮🇱' },
  { code: '+39', country: 'Italy', countryar: 'إيطاليا', flag: '🇮🇹' },
  { code: '+225', country: 'Ivory Coast', countryar: 'ساحل العاج', flag: '🇨🇮' },
  { code: '+1-876', country: 'Jamaica', countryar: 'جامايكا', flag: '🇯🇲' },
  { code: '+81', country: 'Japan', countryar: 'اليابان', flag: '🇯🇵' },
  { code: '+44-1534', country: 'Jersey', countryar: 'جيرسي', flag: '🇯🇪' },
  { code: '+962', country: 'Jordan', countryar: 'الأردن', flag: '🇯🇴' },
  { code: '+7', country: 'Kazakhstan', countryar: 'كازاخستان', flag: '🇰🇿' },
  { code: '+254', country: 'Kenya', countryar: 'كينيا', flag: '🇰🇪' },
  { code: '+686', country: 'Kiribati', countryar: 'كيريباتي', flag: '🇰🇮' },
  { code: '+383', country: 'Kosovo', countryar: 'كوسوفو', flag: '🇽🇰' },
  { code: '+965', country: 'Kuwait', countryar: 'الكويت', flag: '🇰🇼' },
  { code: '+996', country: 'Kyrgyzstan', countryar: 'قيرغيزستان', flag: '🇰🇬' },
  { code: '+856', country: 'Laos', countryar: 'لاوس', flag: '🇱🇦' },
  { code: '+371', country: 'Latvia', countryar: 'لاتفيا', flag: '🇱🇻' },
  { code: '+961', country: 'Lebanon', countryar: 'لبنان', flag: '🇱🇧' },
  { code: '+266', country: 'Lesotho', countryar: 'ليسوتو', flag: '🇱🇸' },
  { code: '+231', country: 'Liberia', countryar: 'ليبيريا', flag: '🇱🇷' },
  { code: '+218', country: 'Libya', countryar: 'ليبيا', flag: '🇱🇾' },
  { code: '+423', country: 'Liechtenstein', countryar: 'ليختنشتاين', flag: '🇱🇮' },
  { code: '+370', country: 'Lithuania', countryar: 'ليتوانيا', flag: '🇱🇹' },
  { code: '+352', country: 'Luxembourg', countryar: 'لوكسمبورغ', flag: '🇱🇺' },
  { code: '+853', country: 'Macau', countryar: 'ماكاو', flag: '🇲🇴' },
  { code: '+389', country: 'North Macedonia', countryar: 'مقدونيا الشمالية', flag: '🇲🇰' },
  { code: '+261', country: 'Madagascar', countryar: 'مدغشقر', flag: '🇲🇬' },
  { code: '+265', country: 'Malawi', countryar: 'مالاوي', flag: '🇲🇼' },
  { code: '+60', country: 'Malaysia', countryar: 'ماليزيا', flag: '🇲🇾' },
  { code: '+960', country: 'Maldives', countryar: 'المالديف', flag: '🇲🇻' },
  { code: '+223', country: 'Mali', countryar: 'مالي', flag: '🇲🇱' },
  { code: '+356', country: 'Malta', countryar: 'مالطا', flag: '🇲🇹' },
  { code: '+692', country: 'Marshall Islands', countryar: 'جزر مارشال', flag: '🇲🇭' },
  { code: '+596', country: 'Martinique', countryar: 'مارتينيك', flag: '🇲🇶' },
  { code: '+222', country: 'Mauritania', countryar: 'موريتانيا', flag: '🇲🇷' },
  { code: '+230', country: 'Mauritius', countryar: 'موريشيوس', flag: '🇲🇺' },
  { code: '+262', country: 'Mayotte', countryar: 'مايوت', flag: '🇾🇹' },
  { code: '+52', country: 'Mexico', countryar: 'المكسيك', flag: '🇲🇽' },
  { code: '+691', country: 'Micronesia', countryar: 'ميكرونيزيا', flag: '🇫🇲' },
  { code: '+373', country: 'Moldova', countryar: 'مولدوفا', flag: '🇲🇩' },
  { code: '+377', country: 'Monaco', countryar: 'موناكو', flag: '🇲🇨' },
  { code: '+976', country: 'Mongolia', countryar: 'منغوليا', flag: '🇲🇳' },
  { code: '+382', country: 'Montenegro', countryar: 'الجبل الأسود', flag: '🇲🇪' },
  { code: '+1-664', country: 'Montserrat', countryar: 'مونتسيرات', flag: '🇲🇸' },
  { code: '+212', country: 'Morocco', countryar: 'المغرب', flag: '🇲🇦' },
  { code: '+258', country: 'Mozambique', countryar: 'موزمبيق', flag: '🇲🇿' },
  { code: '+95', country: 'Myanmar', countryar: 'ميانمار', flag: '🇲🇲' },
  { code: '+264', country: 'Namibia', countryar: 'ناميبيا', flag: '🇳🇦' },
  { code: '+674', country: 'Nauru', countryar: 'ناورو', flag: '🇳🇷' },
  { code: '+977', country: 'Nepal', countryar: 'نيبال', flag: '🇳🇵' },
  { code: '+31', country: 'Netherlands', countryar: 'هولندا', flag: '🇳🇱' },
  { code: '+687', country: 'New Caledonia', countryar: 'كاليدونيا الجديدة', flag: '🇳🇨' },
  { code: '+64', country: 'New Zealand', countryar: 'نيوزيلندا', flag: '🇳🇿' },
  { code: '+505', country: 'Nicaragua', countryar: 'نيكاراغوا', flag: '🇳🇮' },
  { code: '+227', country: 'Niger', countryar: 'النيجر', flag: '🇳🇪' },
  { code: '+234', country: 'Nigeria', countryar: 'نيجيريا', flag: '🇳🇬' },
  { code: '+683', country: 'Niue', countryar: 'نيوي', flag: '🇳🇺' },
  { code: '+850', country: 'North Korea', countryar: 'كوريا الشمالية', flag: '🇰🇵' },
  { code: '+1-670', country: 'Northern Mariana Islands', countryar: 'جزر ماريانا الشمالية', flag: '🇲🇵' },
  { code: '+47', country: 'Norway', countryar: 'النرويج', flag: '🇳🇴' },
  { code: '+968', country: 'Oman', countryar: 'عمان', flag: '🇴🇲' },
  { code: '+92', country: 'Pakistan', countryar: 'باكستان', flag: '🇵🇰' },
  { code: '+680', country: 'Palau', countryar: 'بالاو', flag: '🇵🇼' },
  { code: '+970', country: 'Palestine', countryar: 'فلسطين', flag: '🇵🇸' },
  { code: '+507', country: 'Panama', countryar: 'بنما', flag: '🇵🇦' },
  { code: '+675', country: 'Papua New Guinea', countryar: 'بابوا غينيا الجديدة', flag: '🇵🇬' },
  { code: '+595', country: 'Paraguay', countryar: 'باراغواي', flag: '🇵🇾' },
  { code: '+51', country: 'Peru', countryar: 'بيرو', flag: '🇵🇪' },
  { code: '+63', country: 'Philippines', countryar: 'الفلبين', flag: '🇵🇭' },
  { code: '+48', country: 'Poland', countryar: 'بولندا', flag: '🇵🇱' },
  { code: '+351', country: 'Portugal', countryar: 'البرتغال', flag: '🇵🇹' },
  { code: '+1-787', country: 'Puerto Rico', countryar: 'بورتو ريكو', flag: '🇵🇷' },
  { code: '+974', country: 'Qatar', countryar: 'قطر', flag: '🇶🇦' },
  { code: '+242', country: 'Republic of the Congo', countryar: 'جمهورية الكونغو', flag: '🇨🇬' },
  { code: '+262', country: 'Réunion', countryar: 'ريونيون', flag: '🇷🇪' },
  { code: '+40', country: 'Romania', countryar: 'رومانيا', flag: '🇷🇴' },
  { code: '+7', country: 'Russia', countryar: 'روسيا', flag: '🇷🇺' },
  { code: '+250', country: 'Rwanda', countryar: 'رواندا', flag: '🇷🇼' },
  { code: '+290', country: 'Saint Helena', countryar: 'سانت هيلينا', flag: '🇸🇭' },
  { code: '+1-869', country: 'Saint Kitts and Nevis', countryar: 'سانت كيتس ونيفيس', flag: '🇰🇳' },
  { code: '+1-758', country: 'Saint Lucia', countryar: 'سانت لوسيا', flag: '🇱🇨' },
  { code: '+508', country: 'Saint Pierre and Miquelon', countryar: 'سان بيير وميكلون', flag: '🇵🇲' },
  { code: '+1-784', country: 'Saint Vincent and the Grenadines', countryar: 'سانت فنسنت وجزر غرينادين', flag: '🇻🇨' },
  { code: '+685', country: 'Samoa', countryar: 'ساموا', flag: '🇼🇸' },
  { code: '+378', country: 'San Marino', countryar: 'سان مارينو', flag: '🇸🇲' },
  { code: '+239', country: 'Sao Tome and Principe', countryar: 'ساو تومي وبرينسيبي', flag: '🇸🇹' },
  { code: '+966', country: 'Saudi Arabia', countryar: 'السعودية', flag: '🇸🇦' },
  { code: '+221', country: 'Senegal', countryar: 'السنغال', flag: '🇸🇳' },
  { code: '+381', country: 'Serbia', countryar: 'صربيا', flag: '🇷🇸' },
  { code: '+248', country: 'Seychelles', countryar: 'سيشيل', flag: '🇸🇨' },
  { code: '+232', country: 'Sierra Leone', countryar: 'سيراليون', flag: '🇸🇱' },
  { code: '+65', country: 'Singapore', countryar: 'سنغافورة', flag: '🇸🇬' },
  { code: '+421', country: 'Slovakia', countryar: 'سلوفاكيا', flag: '🇸🇰' },
  { code: '+386', country: 'Slovenia', countryar: 'سلوفينيا', flag: '🇸🇮' },
  { code: '+677', country: 'Solomon Islands', countryar: 'جزر سليمان', flag: '🇸🇧' },
  { code: '+252', country: 'Somalia', countryar: 'الصومال', flag: '🇸🇴' },
  { code: '+27', country: 'South Africa', countryar: 'جنوب أفريقيا', flag: '🇿🇦' },
  { code: '+82', country: 'South Korea', countryar: 'كوريا الجنوبية', flag: '🇰🇷' },
  { code: '+211', country: 'South Sudan', countryar: 'جنوب السودان', flag: '🇸🇸' },
  { code: '+34', country: 'Spain', countryar: 'إسبانيا', flag: '🇪🇸' },
  { code: '+94', country: 'Sri Lanka', countryar: 'سريلانكا', flag: '🇱🇰' },
  { code: '+249', country: 'Sudan', countryar: 'السودان', flag: '🇸🇩' },
  { code: '+597', country: 'Suriname', countryar: 'سورينام', flag: '🇸🇷' },
  { code: '+47', country: 'Svalbard and Jan Mayen', countryar: 'سفالبارد ويان ماين', flag: '🇸🇯' },
  { code: '+268', country: 'Eswatini', countryar: 'إسواتيني', flag: '🇸🇿' },
  { code: '+46', country: 'Sweden', countryar: 'السويد', flag: '🇸🇪' },
  { code: '+41', country: 'Switzerland', countryar: 'سويسرا', flag: '🇨🇭' },
  { code: '+963', country: 'Syria', countryar: 'سوريا', flag: '🇸🇾' },
  { code: '+886', country: 'Taiwan', countryar: 'تايوان', flag: '🇹🇼' },
  { code: '+992', country: 'Tajikistan', countryar: 'طاجيكستان', flag: '🇹🇯' },
  { code: '+255', country: 'Tanzania', countryar: 'تنزانيا', flag: '🇹🇿' },
  { code: '+66', country: 'Thailand', countryar: 'تايلاند', flag: '🇹🇭' },
  { code: '+228', country: 'Togo', countryar: 'توغو', flag: '🇹🇬' },
  { code: '+690', country: 'Tokelau', countryar: 'توكيلاو', flag: '🇹🇰' },
  { code: '+676', country: 'Tonga', countryar: 'تونغا', flag: '🇹🇴' },
  { code: '+1-868', country: 'Trinidad and Tobago', countryar: 'ترينيداد وتوباغو', flag: '🇹🇹' },
  { code: '+216', country: 'Tunisia', countryar: 'تونس', flag: '🇹🇳' },
  { code: '+90', country: 'Turkey', countryar: 'تركيا', flag: '🇹🇷' },
  { code: '+993', country: 'Turkmenistan', countryar: 'تركمانستان', flag: '🇹🇲' },
  { code: '+1-649', country: 'Turks and Caicos Islands', countryar: 'جزر تركس وكايكوس', flag: '🇹🇨' },
  { code: '+688', country: 'Tuvalu', countryar: 'توفالو', flag: '🇹🇻' },
  { code: '+256', country: 'Uganda', countryar: 'أوغندا', flag: '🇺🇬' },
  { code: '+380', country: 'Ukraine', countryar: 'أوكرانيا', flag: '🇺🇦' },
  { code: '+971', country: 'United Arab Emirates', countryar: 'الإمارات العربية المتحدة', flag: '🇦🇪' },
  { code: '+44', country: 'United Kingdom', countryar: 'المملكة المتحدة', flag: '🇬🇧' },
  { code: '+1', country: 'United States', countryar: 'الولايات المتحدة', flag: '🇺🇸' },
  { code: '+598', country: 'Uruguay', countryar: 'أوروغواي', flag: '🇺🇾' },
  { code: '+998', country: 'Uzbekistan', countryar: 'أوزبكستان', flag: '🇺🇿' },
  { code: '+678', country: 'Vanuatu', countryar: 'فانواتو', flag: '🇻🇺' },
  { code: '+379', country: 'Vatican City', countryar: 'مدينة الفاتيكان', flag: '🇻🇦' },
  { code: '+58', country: 'Venezuela', countryar: 'فنزويلا', flag: '🇻🇪' },
  { code: '+84', country: 'Vietnam', countryar: 'فيتنام', flag: '🇻🇳' },
  { code: '+681', country: 'Wallis and Futuna', countryar: 'واليس وفوتونا', flag: '🇼🇫' },
  { code: '+212', country: 'Western Sahara', countryar: 'الصحراء الغربية', flag: '🇪🇭' },
  { code: '+967', country: 'Yemen', countryar: 'اليمن', flag: '🇾🇪' },
  { code: '+260', country: 'Zambia', countryar: 'زامبيا', flag: '🇿🇲' },
  { code: '+263', country: 'Zimbabwe', countryar: 'زيمبابوي', flag: '🇿🇼' }
]